


main:
	cd Área\ de\ Trabalho/ &&
	cd 20232-TEAM-9/ &&
	cd TESTE/ &&
	g++ mainteste.cpp pessoa.cpp pessoajuridica.cpp contabilidade_fisica.cpp contabilidade_juridica.cpp juridica_comercial.cpp juridica_industrial.cpp juridica_prestservico.cpp -o main